# Files to excludes from your website
theme: minima
exclude:
  - Changelog.md
  plugins:
  - jekyll-titles-from-headings
titles_from_headings:
  - enabled:     false
  - strip_title: false
  - collections: false
#remote_theme: pages-themes/hacker@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
